spring:
#  sql:
#    init:
#      mode: always
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/medium_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  data:
    redis:
      port: 6379
      host: localhost
logging:
  level:
    com.ll.medium: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.springframework.web: DEBUG
custom:
  site:
    name: medium
    baseUrl: "http://localhost:8090"
  tempDirPath: c:/temp/medium_dev/temp
  genFile:
    dirPath: /Users/chanw12/Documents

jwt:
  header: Authorization
