spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:medium_test;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
custom:
  tempDirPath: /Users/chanw12/Documents/temp
  genFile:
    dirPath: /Users/chanw12/Documents
